### PR TITLE
Added test cases for Payment Gateway

### PR DESCRIPTION
**Pull request by neelshah2409**
I had added some new test cases in csv file.

Issue Number: #61

### CODE REVIEW

**Comment by Chhavig28** [comment]
@neelshah2409 There are few duplicate cases. Could you please remove those and add few more cases?

**Comment by neelshah2409** [comment]
@Chhavig28 Sir Please review the changes.

**Comment by Chhavig28** [comment]
@neelshah2409 Could you please remove the duplicate cases like 26th and few others?

**Comment by neelshah2409** [comment]
@Chhavig28 Please see it .

**Comment by Chhavig28** [comment]
@neelshah2409 Thanks for contributing. Your PR is accepted for the Hacktoberfest. Please fill this [form](https://forms.gle/qhG6Sf8qrBznRrtQA) to become eligible for LoginRadius cool swags. :)

**Pull request closed without merging**
